### ISSUE TITLE
Piazza / other class forum?

### ISSUE THREAD

**Issue by kazimuth** [SciML/SciMLBook#1]
I'd like to look for people to work with, is there a forum we can use to look for people?

**Comment by ChrisRackauckas** [comment]
Yes, I should've made note of this. We will use the channel #sciml in the Julialang Slack. To get an account you just ask for one here: https://slackinvite.julialang.org/

Also, feel free to ask questions on the Julia Discourse: https://discourse.julialang.org/.

**Comment by logankilpatrick** [comment]
The new Slack URL is https://julialang.org/slack/
