### ISSUE TITLE
Chapter 8: The title array of structs should probably be struct of arrays instead of array of structs.

### ISSUE THREAD

**Issue by loonatick-src** [SciML/SciMLBook#133]
**Suggestion**

The subtitle reads "Array of Structs Representation". But, the section describes using a struct of arrays representation instead. The title should probably be changed to "Struct of Arrays Representation".
**Identification**

- Chapter 8

- Section: "Array of Structs Representation"

**Correction**

The subtitle reads "Array of Structs Representation". But, the first sentence is "Instead of thinking about a vector of dual numbers, thus we can instead think of dual numbers with vectors for the components", which describes a struct of arrays (SoA) representation. Also, the `\hdots` in the equation just after this paragraph is not rendering on my browser (Firefox 116.0.1).
**Screenshots**

![image](https://github.com/SciML/SciMLBook/assets/51789253/ef511f00-4be9-4d5a-b7bd-fbf0203c3f57)

**Comment by ChrisRackauckas** [comment]
Agreed both look like an error
