### ISSUE TITLE
Flux not Precompiling in when running Julia v1.10

### ISSUE THREAD

**Issue by ajahraus** [SciML/SciMLBook#140]
**Suggestion**

Flux is not precompling when run with Julia 1.10

**Identification**

Lecture 03 

`Getting Started with Machine Learning: Adding Flux`
As well as other cells which are dependent on Flux

**Correction**

I'm not actually sure exactly what the solution to the problem is, but the correct behaviour is for Flux to import properly and not throw an error 😉 

**Screenshots**

![image](https://github.com/SciML/SciMLBook/assets/9949357/8c29d8bb-54ca-4ca9-b975-d8537a3ecf32)

**Comment by ChrisRackauckas** [comment]
It needed some versions bumps, https://github.com/SciML/SciMLBook/pull/141
