### ISSUE TITLE
Typo + mistake? 

### ISSUE THREAD

**Issue by VincentMeijer** [SciML/SciMLBook#43]
"Recal" should be "recall"
https://github.com/SciML/SciMLBook/blob/84c99703be244b672dd9480714892948a32ea306/_weave/lecture08/automatic_differentiation.jmd#L120

Here, I wonder whether "imaginary" should be "complex"?
https://github.com/SciML/SciMLBook/blob/84c99703be244b672dd9480714892948a32ea306/_weave/lecture08/automatic_differentiation.jmd#L121

**Comment by ChrisRackauckas** [comment]
yes and yes
