### ISSUE TITLE
Chapter enumeration

### ISSUE THREAD

**Issue by Sciemon** [SciML/SciMLBook#48]
It seems that Ch. 12 went missing.
Furthermore, it would be nice to have the number of a Chapter displayed together with the heading at the top (or indicate the current chapter in some other way) to make navigation easier (maybe this is an issue of Weave).

Other than that, great course and thanks a lot for sharing!!

**Comment by ChrisRackauckas** [comment]
12 is the MPI notes from here: https://github.com/SciML/SciMLBook/blob/master/lectures/index.md#lecture-12-sciml-in-practice. Maybe just creating a page and linking to the PDF is sufficient for now.
