### ISSUE TITLE
Fix Typo: Chpt. 15, Hamiltonian MC

### ISSUE THREAD

**Issue by kcarloni** [SciML/SciMLBook#60]
**Suggest Correction**
Pretty sure eq (4) should read \dot{p} = - dH/dx; currently the left side of this equation is missing (making it look like dH/dp = -dH/dx).

**Identify**
Chapter 15, the section on Hamiltonian Monte Carlo.

**Comment by Rishikesh2338** [comment]
Please assign me this work

**Comment by ChrisRackauckas** [comment]
No need for assignments, please just open the PR

**Comment by Rishikesh233** [comment]
can you please tell me how to do that as I am new to open source contributor field

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/SciMLBook/pull/102 thanks!
