### ISSUE TITLE
Move lectures up to the top to align with left menu

### ISSUE THREAD

**Issue by alanedelman** [SciML/SciMLBook#63]
in the screenshot the 19 is above the "Optimizing serial code" creating an annoying need to scroll down just
to even see the title.  Great if lectures can be moved up.
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/862530/165579787-31a21d9d-e7c9-40d1-b4fd-cf34da2ed969.png">

**Comment by ChrisRackauckas** [comment]
@jvaverka do you know which update did that? I don't remember it always being like that.

**Comment by jvaverka** [comment]
This only occurs for certain screen dimensions. Hadn't come across this screen resolution before now. Tweaking the [media queries](https://github.com/SciML/SciMLBook/blob/f2a5673a326ac040a3dc30915f1f65718da1e043/_css/adjust.css#L58-L89) should correct this issue on screens with quirky aspect ratios.

**Comment by jvaverka** [comment]
My commit above fixes the annoying issue, but I have ideas on how to make better use of screen real estate & maybe improve #57
