### ISSUE TITLE
derivation mistake in note 11

### ISSUE THREAD

**Issue by HoshiSora-95** [SciML/SciMLBook#68]
**Suggestion**
derivation mistake on ODE adjoints

**Identification**
Notes 11

**Correction**

$$
\int_{t_{0}}^{T}\lambda^{\ast}\left(s^{\prime}-f_{u}s-f_{p}\right)dt	=\int_{t_{0}}^{T}\lambda^{\ast}s^{\prime}dt-\int_{t_{0}}^{T}\lambda^{\ast}\left(f_{u}s-f_{p}\right)dt
$$

should be 

$$
\int_{t_{0}}^{T}\lambda^{\ast}\left(s^{\prime}-f_{u}s-f_{p}\right)dt	=\int_{t_{0}}^{T}\lambda^{\ast}s^{\prime}dt-\int_{t_{0}}^{T}\lambda^{\ast}\left(f_{u}s+f_{p}\right)dt
$$

and that affects the latter derivations.

**Screenshots**

**Additional context**

**Comment by ChrisRackauckas** [comment]
Yes, I think I had a sign error. I noticed it when lecturing but haven't gotten back to correct it. A PR would be helpful.
