### ISSUE TITLE
Lecture 8 Notes has wrong link

### ISSUE THREAD

**Issue by arav-agarwal2** [SciML/SciMLBook#69]
When I navigate to lecture 8 (Forward Mode AD), I get navigated to:

https://book.sciml.ai/notes/08-Forward-Mode_Automatic_Differentiation_/

which returns a 404 error.

However, it looks like the correct link is:

https://book.sciml.ai/notes/08-Forward-Mode_Automatic_Differentiation_(AD)_via_High_Dimensional_Algebras/

**Comment by ChrisRackauckas** [comment]
Thanks!
